# Generated by Django 5.0.4 on 2025-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="staus",
            field=models.CharField(default="Open", max_length=20),
        ),
    ]
