# Generated by Django 5.0.4 on 2025-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guests",
            field=models.IntegerField(default=0),
        ),
    ]
