# Generated by Django 5.0.4 on 2025-07-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_booking_guests"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="assigned_restaurant",
            new_name="restaurant",
        ),
    ]
