# Generated by Django 5.0.4 on 2025-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_rename_assigned_restaurant_employee_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(default="test@example.com", max_length=254),
        ),
    ]
