# Generated by Django 5.0.4 on 2025-07-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_restaurant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default="test@example.com", max_length=254),
        ),
    ]
