# Generated by Django 5.0.4 on 2025-07-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_menuitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="user",
            new_name="head",
        ),
    ]
