# Generated by Django 5.0.4 on 2025-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_rename_user_restaurant_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant_images/"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="service_options",
            field=models.TextField(
                blank=True,
                help_text="e.g. All you can Eat . Outdoor seating . Vegan options",
            ),
        ),
    ]
